[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_THEME = "blixem"
  HUGO_BASEURL = "https://blixem-hugo-theme.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
